/*
 * Immutable X API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = api.Client.OpenAPIDateConverter;

namespace api.Model
{
    /// <summary>
    /// CreateTransferResponse
    /// </summary>
    [DataContract(Name = "CreateTransferResponse")]
    public partial class CreateTransferResponse : IEquatable<CreateTransferResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTransferResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateTransferResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTransferResponse" /> class.
        /// </summary>
        /// <param name="transferIds">List of transfer IDs (required).</param>
        public CreateTransferResponse(List<int> transferIds = default(List<int>))
        {
            // to ensure "transferIds" is required (not null)
            if (transferIds == null)
            {
                throw new ArgumentNullException("transferIds is a required property for CreateTransferResponse and cannot be null");
            }
            this.TransferIds = transferIds;
        }

        /// <summary>
        /// List of transfer IDs
        /// </summary>
        /// <value>List of transfer IDs</value>
        [DataMember(Name = "transfer_ids", IsRequired = true, EmitDefaultValue = true)]
        public List<int> TransferIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTransferResponse {\n");
            sb.Append("  TransferIds: ").Append(TransferIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateTransferResponse);
        }

        /// <summary>
        /// Returns true if CreateTransferResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateTransferResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateTransferResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TransferIds == input.TransferIds ||
                    this.TransferIds != null &&
                    input.TransferIds != null &&
                    this.TransferIds.SequenceEqual(input.TransferIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransferIds != null)
                {
                    hashCode = (hashCode * 59) + this.TransferIds.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
