/*
 * Immutable X API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = api.Client.OpenAPIDateConverter;

namespace api.Model
{
    /// <summary>
    /// NftprimarytransactionGetResponse
    /// </summary>
    [DataContract(Name = "nftprimarytransaction.GetResponse")]
    public partial class NftprimarytransactionGetResponse : IEquatable<NftprimarytransactionGetResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NftprimarytransactionGetResponse" /> class.
        /// </summary>
        /// <param name="contractAddress">Contract address of the asset.</param>
        /// <param name="offerId">Temporary asset id. Might be a token id if the token id is known or a generic description if it&#39;s not.</param>
        /// <param name="provider">Provider name.</param>
        /// <param name="sellerWalletAddress">Ethereum address of the seller.</param>
        /// <param name="status">Transaction status enums(created, waitingPayment, pending, completed, failed).</param>
        /// <param name="tokenId">ID of the token that has been successfully minted - might or not be the same as &#x60;offer_id&#x60;.</param>
        /// <param name="transactionId">Transaction id.</param>
        /// <param name="userWalletAddress">Wallet address that receives the minted NFT.</param>
        public NftprimarytransactionGetResponse(string contractAddress = default(string), string offerId = default(string), string provider = default(string), string sellerWalletAddress = default(string), string status = default(string), string tokenId = default(string), string transactionId = default(string), string userWalletAddress = default(string))
        {
            this.ContractAddress = contractAddress;
            this.OfferId = offerId;
            this.Provider = provider;
            this.SellerWalletAddress = sellerWalletAddress;
            this.Status = status;
            this.TokenId = tokenId;
            this.TransactionId = transactionId;
            this.UserWalletAddress = userWalletAddress;
        }

        /// <summary>
        /// Contract address of the asset
        /// </summary>
        /// <value>Contract address of the asset</value>
        [DataMember(Name = "contract_address", EmitDefaultValue = false)]
        public string ContractAddress { get; set; }

        /// <summary>
        /// Temporary asset id. Might be a token id if the token id is known or a generic description if it&#39;s not
        /// </summary>
        /// <value>Temporary asset id. Might be a token id if the token id is known or a generic description if it&#39;s not</value>
        [DataMember(Name = "offer_id", EmitDefaultValue = false)]
        public string OfferId { get; set; }

        /// <summary>
        /// Provider name
        /// </summary>
        /// <value>Provider name</value>
        [DataMember(Name = "provider", EmitDefaultValue = false)]
        public string Provider { get; set; }

        /// <summary>
        /// Ethereum address of the seller
        /// </summary>
        /// <value>Ethereum address of the seller</value>
        [DataMember(Name = "seller_wallet_address", EmitDefaultValue = false)]
        public string SellerWalletAddress { get; set; }

        /// <summary>
        /// Transaction status enums(created, waitingPayment, pending, completed, failed)
        /// </summary>
        /// <value>Transaction status enums(created, waitingPayment, pending, completed, failed)</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// ID of the token that has been successfully minted - might or not be the same as &#x60;offer_id&#x60;
        /// </summary>
        /// <value>ID of the token that has been successfully minted - might or not be the same as &#x60;offer_id&#x60;</value>
        [DataMember(Name = "token_id", EmitDefaultValue = false)]
        public string TokenId { get; set; }

        /// <summary>
        /// Transaction id
        /// </summary>
        /// <value>Transaction id</value>
        [DataMember(Name = "transaction_id", EmitDefaultValue = false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Wallet address that receives the minted NFT
        /// </summary>
        /// <value>Wallet address that receives the minted NFT</value>
        [DataMember(Name = "user_wallet_address", EmitDefaultValue = false)]
        public string UserWalletAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NftprimarytransactionGetResponse {\n");
            sb.Append("  ContractAddress: ").Append(ContractAddress).Append("\n");
            sb.Append("  OfferId: ").Append(OfferId).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  SellerWalletAddress: ").Append(SellerWalletAddress).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TokenId: ").Append(TokenId).Append("\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  UserWalletAddress: ").Append(UserWalletAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NftprimarytransactionGetResponse);
        }

        /// <summary>
        /// Returns true if NftprimarytransactionGetResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of NftprimarytransactionGetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NftprimarytransactionGetResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ContractAddress == input.ContractAddress ||
                    (this.ContractAddress != null &&
                    this.ContractAddress.Equals(input.ContractAddress))
                ) && 
                (
                    this.OfferId == input.OfferId ||
                    (this.OfferId != null &&
                    this.OfferId.Equals(input.OfferId))
                ) && 
                (
                    this.Provider == input.Provider ||
                    (this.Provider != null &&
                    this.Provider.Equals(input.Provider))
                ) && 
                (
                    this.SellerWalletAddress == input.SellerWalletAddress ||
                    (this.SellerWalletAddress != null &&
                    this.SellerWalletAddress.Equals(input.SellerWalletAddress))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.TokenId == input.TokenId ||
                    (this.TokenId != null &&
                    this.TokenId.Equals(input.TokenId))
                ) && 
                (
                    this.TransactionId == input.TransactionId ||
                    (this.TransactionId != null &&
                    this.TransactionId.Equals(input.TransactionId))
                ) && 
                (
                    this.UserWalletAddress == input.UserWalletAddress ||
                    (this.UserWalletAddress != null &&
                    this.UserWalletAddress.Equals(input.UserWalletAddress))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContractAddress != null)
                {
                    hashCode = (hashCode * 59) + this.ContractAddress.GetHashCode();
                }
                if (this.OfferId != null)
                {
                    hashCode = (hashCode * 59) + this.OfferId.GetHashCode();
                }
                if (this.Provider != null)
                {
                    hashCode = (hashCode * 59) + this.Provider.GetHashCode();
                }
                if (this.SellerWalletAddress != null)
                {
                    hashCode = (hashCode * 59) + this.SellerWalletAddress.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.TokenId != null)
                {
                    hashCode = (hashCode * 59) + this.TokenId.GetHashCode();
                }
                if (this.TransactionId != null)
                {
                    hashCode = (hashCode * 59) + this.TransactionId.GetHashCode();
                }
                if (this.UserWalletAddress != null)
                {
                    hashCode = (hashCode * 59) + this.UserWalletAddress.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
