generatorName: csharp-netcore
inputSpec: openapi.json
gitHost: github.com
gitUserId: immutable
gitRepoId: imx-core-sdk-csharp
enablePostProcessFile: true
additionalProperties:
  packageName: Imx.Sdk.Gen
  packageVersion: 0.1.1   # Todo: Auto generate this version string from the release git tags.
  netCoreProjectFile: true
  Default: true
  targetFramework: netstandard2.1;net6.0