/*
 * Immutable X API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using api.Client;
using api.Model;

namespace api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEncodingApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieves the Starkex Encoded format for a given asset
        /// </summary>
        /// <remarks>
        /// Retrieves the Starkex Encoded format for a given asset so that it can be used as parameter for Starkex smart contracts
        /// </remarks>
        /// <exception cref="api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetType">Asset type to be encoded. (asset/mintable-asset)</param>
        /// <param name="encodeAssetRequest">Encode Asset</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EncodeAssetResponse</returns>
        EncodeAssetResponse EncodeAsset(string assetType, EncodeAssetRequest encodeAssetRequest, int operationIndex = 0);

        /// <summary>
        /// Retrieves the Starkex Encoded format for a given asset
        /// </summary>
        /// <remarks>
        /// Retrieves the Starkex Encoded format for a given asset so that it can be used as parameter for Starkex smart contracts
        /// </remarks>
        /// <exception cref="api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetType">Asset type to be encoded. (asset/mintable-asset)</param>
        /// <param name="encodeAssetRequest">Encode Asset</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EncodeAssetResponse</returns>
        ApiResponse<EncodeAssetResponse> EncodeAssetWithHttpInfo(string assetType, EncodeAssetRequest encodeAssetRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEncodingApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves the Starkex Encoded format for a given asset
        /// </summary>
        /// <remarks>
        /// Retrieves the Starkex Encoded format for a given asset so that it can be used as parameter for Starkex smart contracts
        /// </remarks>
        /// <exception cref="api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetType">Asset type to be encoded. (asset/mintable-asset)</param>
        /// <param name="encodeAssetRequest">Encode Asset</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EncodeAssetResponse</returns>
        System.Threading.Tasks.Task<EncodeAssetResponse> EncodeAssetAsync(string assetType, EncodeAssetRequest encodeAssetRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retrieves the Starkex Encoded format for a given asset
        /// </summary>
        /// <remarks>
        /// Retrieves the Starkex Encoded format for a given asset so that it can be used as parameter for Starkex smart contracts
        /// </remarks>
        /// <exception cref="api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetType">Asset type to be encoded. (asset/mintable-asset)</param>
        /// <param name="encodeAssetRequest">Encode Asset</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EncodeAssetResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<EncodeAssetResponse>> EncodeAssetWithHttpInfoAsync(string assetType, EncodeAssetRequest encodeAssetRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEncodingApi : IEncodingApiSync, IEncodingApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EncodingApi : IEncodingApi
    {
        private api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EncodingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EncodingApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EncodingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EncodingApi(string basePath)
        {
            this.Configuration = api.Client.Configuration.MergeConfigurations(
                api.Client.GlobalConfiguration.Instance,
                new api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EncodingApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EncodingApi(api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = api.Client.Configuration.MergeConfigurations(
                api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EncodingApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public EncodingApi(api.Client.ISynchronousClient client, api.Client.IAsynchronousClient asyncClient, api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieves the Starkex Encoded format for a given asset Retrieves the Starkex Encoded format for a given asset so that it can be used as parameter for Starkex smart contracts
        /// </summary>
        /// <exception cref="api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetType">Asset type to be encoded. (asset/mintable-asset)</param>
        /// <param name="encodeAssetRequest">Encode Asset</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EncodeAssetResponse</returns>
        public EncodeAssetResponse EncodeAsset(string assetType, EncodeAssetRequest encodeAssetRequest, int operationIndex = 0)
        {
            api.Client.ApiResponse<EncodeAssetResponse> localVarResponse = EncodeAssetWithHttpInfo(assetType, encodeAssetRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves the Starkex Encoded format for a given asset Retrieves the Starkex Encoded format for a given asset so that it can be used as parameter for Starkex smart contracts
        /// </summary>
        /// <exception cref="api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetType">Asset type to be encoded. (asset/mintable-asset)</param>
        /// <param name="encodeAssetRequest">Encode Asset</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EncodeAssetResponse</returns>
        public api.Client.ApiResponse<EncodeAssetResponse> EncodeAssetWithHttpInfo(string assetType, EncodeAssetRequest encodeAssetRequest, int operationIndex = 0)
        {
            // verify the required parameter 'assetType' is set
            if (assetType == null)
            {
                throw new api.Client.ApiException(400, "Missing required parameter 'assetType' when calling EncodingApi->EncodeAsset");
            }

            // verify the required parameter 'encodeAssetRequest' is set
            if (encodeAssetRequest == null)
            {
                throw new api.Client.ApiException(400, "Missing required parameter 'encodeAssetRequest' when calling EncodingApi->EncodeAsset");
            }

            api.Client.RequestOptions localVarRequestOptions = new api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("assetType", api.Client.ClientUtils.ParameterToString(assetType)); // path parameter
            localVarRequestOptions.Data = encodeAssetRequest;

            localVarRequestOptions.Operation = "EncodingApi.EncodeAsset";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<EncodeAssetResponse>("/v1/encode/{assetType}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EncodeAsset", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves the Starkex Encoded format for a given asset Retrieves the Starkex Encoded format for a given asset so that it can be used as parameter for Starkex smart contracts
        /// </summary>
        /// <exception cref="api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetType">Asset type to be encoded. (asset/mintable-asset)</param>
        /// <param name="encodeAssetRequest">Encode Asset</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EncodeAssetResponse</returns>
        public async System.Threading.Tasks.Task<EncodeAssetResponse> EncodeAssetAsync(string assetType, EncodeAssetRequest encodeAssetRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            api.Client.ApiResponse<EncodeAssetResponse> localVarResponse = await EncodeAssetWithHttpInfoAsync(assetType, encodeAssetRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves the Starkex Encoded format for a given asset Retrieves the Starkex Encoded format for a given asset so that it can be used as parameter for Starkex smart contracts
        /// </summary>
        /// <exception cref="api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetType">Asset type to be encoded. (asset/mintable-asset)</param>
        /// <param name="encodeAssetRequest">Encode Asset</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EncodeAssetResponse)</returns>
        public async System.Threading.Tasks.Task<api.Client.ApiResponse<EncodeAssetResponse>> EncodeAssetWithHttpInfoAsync(string assetType, EncodeAssetRequest encodeAssetRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'assetType' is set
            if (assetType == null)
            {
                throw new api.Client.ApiException(400, "Missing required parameter 'assetType' when calling EncodingApi->EncodeAsset");
            }

            // verify the required parameter 'encodeAssetRequest' is set
            if (encodeAssetRequest == null)
            {
                throw new api.Client.ApiException(400, "Missing required parameter 'encodeAssetRequest' when calling EncodingApi->EncodeAsset");
            }


            api.Client.RequestOptions localVarRequestOptions = new api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("assetType", api.Client.ClientUtils.ParameterToString(assetType)); // path parameter
            localVarRequestOptions.Data = encodeAssetRequest;

            localVarRequestOptions.Operation = "EncodingApi.EncodeAsset";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<EncodeAssetResponse>("/v1/encode/{assetType}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EncodeAsset", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
