/*
 * Immutable X API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Imx.Sdk.Gen.Client.OpenAPIDateConverter;

namespace Imx.Sdk.Gen.Model
{
    /// <summary>
    /// OrderDetails
    /// </summary>
    [DataContract(Name = "OrderDetails")]
    public partial class OrderDetails : IEquatable<OrderDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderDetails" /> class.
        /// </summary>
        /// <param name="buyOrders">Buy orders for this asset.</param>
        /// <param name="sellOrders">Sell orders for this asset.</param>
        public OrderDetails(List<Object> buyOrders = default(List<Object>), List<Object> sellOrders = default(List<Object>))
        {
            this.BuyOrders = buyOrders;
            this.SellOrders = sellOrders;
        }

        /// <summary>
        /// Buy orders for this asset
        /// </summary>
        /// <value>Buy orders for this asset</value>
        [DataMember(Name = "buy_orders", EmitDefaultValue = false)]
        public List<Object> BuyOrders { get; set; }

        /// <summary>
        /// Sell orders for this asset
        /// </summary>
        /// <value>Sell orders for this asset</value>
        [DataMember(Name = "sell_orders", EmitDefaultValue = false)]
        public List<Object> SellOrders { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderDetails {\n");
            sb.Append("  BuyOrders: ").Append(BuyOrders).Append("\n");
            sb.Append("  SellOrders: ").Append(SellOrders).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrderDetails);
        }

        /// <summary>
        /// Returns true if OrderDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of OrderDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderDetails input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BuyOrders == input.BuyOrders ||
                    this.BuyOrders != null &&
                    input.BuyOrders != null &&
                    this.BuyOrders.SequenceEqual(input.BuyOrders)
                ) && 
                (
                    this.SellOrders == input.SellOrders ||
                    this.SellOrders != null &&
                    input.SellOrders != null &&
                    this.SellOrders.SequenceEqual(input.SellOrders)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BuyOrders != null)
                {
                    hashCode = (hashCode * 59) + this.BuyOrders.GetHashCode();
                }
                if (this.SellOrders != null)
                {
                    hashCode = (hashCode * 59) + this.SellOrders.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
