/*
 * Immutable X API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Imx.Sdk.Gen.Client.OpenAPIDateConverter;

namespace Imx.Sdk.Gen.Model
{
    /// <summary>
    /// TransferRequest
    /// </summary>
    [DataContract(Name = "TransferRequest")]
    public partial class TransferRequest : IEquatable<TransferRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransferRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferRequest" /> class.
        /// </summary>
        /// <param name="amount">Amount to transfer (required).</param>
        /// <param name="assetId">ID of the asset to transfer (required).</param>
        /// <param name="expirationTimestamp">Expiration timestamp for this transfer (required).</param>
        /// <param name="nonce">Nonce of the transfer (required).</param>
        /// <param name="receiverStarkKey">Public stark key of the user receiving the transfer (required).</param>
        /// <param name="receiverVaultId">ID of the vault into which the asset will be transferred to (required).</param>
        /// <param name="senderVaultId">ID of the vault into which the asset is from (required).</param>
        /// <param name="starkSignature">Transfer payload signature (required).</param>
        public TransferRequest(string amount = default(string), string assetId = default(string), int expirationTimestamp = default(int), int nonce = default(int), string receiverStarkKey = default(string), int receiverVaultId = default(int), int senderVaultId = default(int), string starkSignature = default(string))
        {
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for TransferRequest and cannot be null");
            }
            this.Amount = amount;
            // to ensure "assetId" is required (not null)
            if (assetId == null)
            {
                throw new ArgumentNullException("assetId is a required property for TransferRequest and cannot be null");
            }
            this.AssetId = assetId;
            this.ExpirationTimestamp = expirationTimestamp;
            this.Nonce = nonce;
            // to ensure "receiverStarkKey" is required (not null)
            if (receiverStarkKey == null)
            {
                throw new ArgumentNullException("receiverStarkKey is a required property for TransferRequest and cannot be null");
            }
            this.ReceiverStarkKey = receiverStarkKey;
            this.ReceiverVaultId = receiverVaultId;
            this.SenderVaultId = senderVaultId;
            // to ensure "starkSignature" is required (not null)
            if (starkSignature == null)
            {
                throw new ArgumentNullException("starkSignature is a required property for TransferRequest and cannot be null");
            }
            this.StarkSignature = starkSignature;
        }

        /// <summary>
        /// Amount to transfer
        /// </summary>
        /// <value>Amount to transfer</value>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public string Amount { get; set; }

        /// <summary>
        /// ID of the asset to transfer
        /// </summary>
        /// <value>ID of the asset to transfer</value>
        [DataMember(Name = "asset_id", IsRequired = true, EmitDefaultValue = true)]
        public string AssetId { get; set; }

        /// <summary>
        /// Expiration timestamp for this transfer
        /// </summary>
        /// <value>Expiration timestamp for this transfer</value>
        [DataMember(Name = "expiration_timestamp", IsRequired = true, EmitDefaultValue = true)]
        public int ExpirationTimestamp { get; set; }

        /// <summary>
        /// Nonce of the transfer
        /// </summary>
        /// <value>Nonce of the transfer</value>
        [DataMember(Name = "nonce", IsRequired = true, EmitDefaultValue = true)]
        public int Nonce { get; set; }

        /// <summary>
        /// Public stark key of the user receiving the transfer
        /// </summary>
        /// <value>Public stark key of the user receiving the transfer</value>
        [DataMember(Name = "receiver_stark_key", IsRequired = true, EmitDefaultValue = true)]
        public string ReceiverStarkKey { get; set; }

        /// <summary>
        /// ID of the vault into which the asset will be transferred to
        /// </summary>
        /// <value>ID of the vault into which the asset will be transferred to</value>
        [DataMember(Name = "receiver_vault_id", IsRequired = true, EmitDefaultValue = true)]
        public int ReceiverVaultId { get; set; }

        /// <summary>
        /// ID of the vault into which the asset is from
        /// </summary>
        /// <value>ID of the vault into which the asset is from</value>
        [DataMember(Name = "sender_vault_id", IsRequired = true, EmitDefaultValue = true)]
        public int SenderVaultId { get; set; }

        /// <summary>
        /// Transfer payload signature
        /// </summary>
        /// <value>Transfer payload signature</value>
        [DataMember(Name = "stark_signature", IsRequired = true, EmitDefaultValue = true)]
        public string StarkSignature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransferRequest {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  ExpirationTimestamp: ").Append(ExpirationTimestamp).Append("\n");
            sb.Append("  Nonce: ").Append(Nonce).Append("\n");
            sb.Append("  ReceiverStarkKey: ").Append(ReceiverStarkKey).Append("\n");
            sb.Append("  ReceiverVaultId: ").Append(ReceiverVaultId).Append("\n");
            sb.Append("  SenderVaultId: ").Append(SenderVaultId).Append("\n");
            sb.Append("  StarkSignature: ").Append(StarkSignature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransferRequest);
        }

        /// <summary>
        /// Returns true if TransferRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TransferRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransferRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.AssetId == input.AssetId ||
                    (this.AssetId != null &&
                    this.AssetId.Equals(input.AssetId))
                ) && 
                (
                    this.ExpirationTimestamp == input.ExpirationTimestamp ||
                    this.ExpirationTimestamp.Equals(input.ExpirationTimestamp)
                ) && 
                (
                    this.Nonce == input.Nonce ||
                    this.Nonce.Equals(input.Nonce)
                ) && 
                (
                    this.ReceiverStarkKey == input.ReceiverStarkKey ||
                    (this.ReceiverStarkKey != null &&
                    this.ReceiverStarkKey.Equals(input.ReceiverStarkKey))
                ) && 
                (
                    this.ReceiverVaultId == input.ReceiverVaultId ||
                    this.ReceiverVaultId.Equals(input.ReceiverVaultId)
                ) && 
                (
                    this.SenderVaultId == input.SenderVaultId ||
                    this.SenderVaultId.Equals(input.SenderVaultId)
                ) && 
                (
                    this.StarkSignature == input.StarkSignature ||
                    (this.StarkSignature != null &&
                    this.StarkSignature.Equals(input.StarkSignature))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Amount != null)
                {
                    hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                }
                if (this.AssetId != null)
                {
                    hashCode = (hashCode * 59) + this.AssetId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ExpirationTimestamp.GetHashCode();
                hashCode = (hashCode * 59) + this.Nonce.GetHashCode();
                if (this.ReceiverStarkKey != null)
                {
                    hashCode = (hashCode * 59) + this.ReceiverStarkKey.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ReceiverVaultId.GetHashCode();
                hashCode = (hashCode * 59) + this.SenderVaultId.GetHashCode();
                if (this.StarkSignature != null)
                {
                    hashCode = (hashCode * 59) + this.StarkSignature.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
