name: Format check on pull request
on:
  pull_request:
permissions:
  contents: read
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Src/IMX/Imx.Sdk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
          
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*

      - name: Run dotnet format
        run: dotnet format --verify-no-changes


