name: Format check on pull request
on:
  pull_request:

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Src/IMX/Imx.Sdk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
          
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
        
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format
        id: format
        uses: jfversluis/dotnet-format@v1.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "check"
          only-changed-files: true

